version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    environtment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - /data:/var/lib/postgresql/data/